---
title: "chi_square_test"
author: "Ruijuan Li"
date: "8/11/2017"
output: 
  html_document: 
    keep_md: yes
---

#### import data 
```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(reshape2)

data <- read.table("~/Desktop/bioinfo_miscs/08-11-2017/note.txt", sep = ",")

data.m1 <- 
data %>%
  separate(V1, into=c("class", "V1"), sep=":")

data.m1
data.m1$V1 <- as.numeric(data.m1$V1)
rownames(data.m1) <- data.m1$class
data.final <- data.m1 %>%
  select(-class)

str(data.final)

# plot the original data 
data.m1 %>%
  melt() %>%
  ggplot() + 
  geom_line(aes(x=variable, y=value, color=class, group=class)) +
  labs(title = "all")

# transform to percentage
data.m1.per <- sapply(data.m1[2:4], function(x) x/rowSums(data.m1[2:4])) %>% as.data.frame() 

data.m1.per$class <- rownames(data.m1.per)

data.m1.per %>%
  melt() %>%
  ggplot() +
  geom_line(aes(x=variable, y=value, color=class, group=class)) +
  labs(title = "percentage")
```

##### chi-square test
I guess you are asking whether choose different emotions are depending on some factors in the column names, if that is the case, here is the result, choosing which emotion is independ of the factors you measured. p-value = 1. 
```{r}
library(MASS)
# on orignal data 
chisq.test(data.final)

# on percentage data 
chisq.test(data.m1.per[,1:3])  
chisq.test(data.m1.per[1,1:3])  

data.final[1,]
chisq.test(data.final[1,])
chisq.test(data.final[2,])
chisq.test(data.final[3,])
chisq.test(data.final[4,])
chisq.test(data.final[5,])
chisq.test(data.final[6,])
chisq.test(data.final[7,]) 
```

